:: Draw a call graph generated by the "Call Graph" extension for VS Code
:: Preparation:
::    Install the "Call Graph" extension by LuoZhihao from the VS Code Extensions.
::    Store a `.callgraphignore` file to exclude unnecessary functions from the call graph.
::    See the bottom of this batch file for an example `.callgraphignore`.
:: Usage:
::    Open the folder containing the .py file in VS Code.
::    Open the .py file from the Explorer view in VS Code.
::    Select a function -> right-click -> Call Graph: Show incoming/outgoing call graph.
::    Click [save dot file].
::    Run this batch file `draw_call_graph.bat` by double-clicking it.
::    An .svg file will be created and opened with the default application.
::    (The recommended application for viewing SVG files is Microsoft Edge.)

call :delete_file_path_from_dot call_graph_outgoing.dot %~dp0
call :delete_file_path_from_dot call_graph_incoming.dot %~dp0

call :replace_dot_settings call_graph_outgoing.dot
call :replace_dot_settings call_graph_incoming.dot

dot -Tsvg call_graph_outgoing.dot -o call_graph_outgoing.svg
dot -Tsvg call_graph_incoming.dot -o call_graph_incoming.svg

start "" /normal call_graph_outgoing.svg >nul 2>nul
start "" /normal call_graph_incoming.svg >nul 2>nul

cmd /k

endlocal
exit

REM ============= Function Definitions =============
:replace_dot_settings
    set "DOTFILE=%~1"

    powershell -NoProfile -ExecutionPolicy Bypass -Command ^
    "$f = '%DOTFILE%';" ^
    "$lines = Get-Content -LiteralPath $f;" ^
    "$idx = ($lines | Select-String -Pattern '^\s*rankdir\s*=\s*""?LR""?' -List).LineNumber - 1;" ^
    "if ($null -eq $idx -or $idx -lt 0) { $idx = ($lines | Select-String -Pattern '^\s*digraph\b.*\{' -List).LineNumber - 1 }" ^
    "if ($null -eq $idx -or $idx -lt 0) { Write-Error 'rankdir や digraph の位置が見つかりません'; exit 1 }" ^
    "$block = @(" ^
    "  'graph ['," ^
    "  '    layout=dot,  /* dot / neato / fdp / sfdp / twopi / circo */'," ^
    "  '    ranksep=2.0,'," ^
    "  '    nodesep=2.0,'," ^
    "  '    splines=ortho'," ^
    "  '];'," ^
    "  'node ['," ^
    "  '    shape=box,'," ^
    "  '    style=filled,'," ^
    "  '    fillcolor=lightyellow,'," ^
    "  '    fontname=""Consolas"",'," ^
    "  '    fontsize=10'," ^
    "  '];'," ^
    "  'edge ['," ^
    "  '    style=solid,'," ^
    "  '    color=gray40,'," ^
    "  '    penwidth=1.2,'," ^
    "  '    arrowsize=0.8'," ^
    "  '];'" ^
    ");" ^
    "$out = @(); $out += $lines[0..$idx]; $out += $block; if ($idx+1 -lt $lines.Count) { $out += $lines[($idx+1)..($lines.Count-1)] };" ^
    "[IO.File]::WriteAllLines($f, $out, (New-Object System.Text.UTF8Encoding($false)))"

     goto :eof

:delete_file_path_from_dot
    set "DOT=%~1"
    set "STRIP=%~2"
    powershell -NoProfile -ExecutionPolicy Bypass -Command ^
    "$f = '%DOT%';" ^
    "$raw = [IO.File]::ReadAllText($f, [Text.Encoding]::UTF8);" ^
    "$p = '%STRIP%';" ^
    "$cands = @();" ^
    "  $p1 = $p -replace '\\','/'; $p1 = $p1.TrimEnd('/');" ^
    "  if ($p1 -ne '') { $cands += $p1 }" ^
    "  if ($p1 -match '^[A-Za-z]:') { $cands += ($p1 -replace '^([A-Za-z]):','/$1:') }" ^
    "  if ($p1 -notmatch '^(?:[A-Za-z]:|/)') { $cands += ('/' + $p1) }" ^
    "$cands = $cands | Select-Object -Unique" ^
    "; foreach ($c in $cands) {" ^
    "    $pat1 = [Regex]::Escape($c + '/');" ^
    "    $pat2 = [Regex]::Escape($c);        " ^
    "    $raw = [Regex]::Replace($raw, $pat1, '', 'IgnoreCase');" ^
    "    $raw = [Regex]::Replace($raw, $pat2, '', 'IgnoreCase');" ^
    "  }" ^
    "[IO.File]::WriteAllText($f, $raw, (New-Object System.Text.UTF8Encoding($false)))"
    
     goto :eof

-- Sample of .callgraphignore --

**/typeshed-fallback /**
**/site-packages /**
**/dist-packages /**
**/Lib /**
**/lib /**
**/Python3*/Lib /**
**/python3*/lib/**